blueprints/apikey.py
from flask import Blueprint, jsonify, render_template, request, session, redirect, url_for
from itsdangerous import URLSafeTimedSerializer
from database.auth_db import upsert_api_key , get_api_key
import os


api_key_bp = Blueprint('api_key_bp', __name__, url_prefix='/')

app_secret_key = os.getenv('APP_KEY')

def generate_api_key(user_id):
    serializer = URLSafeTimedSerializer(app_secret_key)
    return serializer.dumps(user_id, salt='api_key')

@api_key_bp.route('/apikey', methods=['GET', 'POST'])
def manage_api_key():
    if not session.get('logged_in'):
        return redirect(url_for('auth.login'))  
    
    if request.method == 'GET':
        login_username = session['user']
        current_api_key = get_api_key(login_username)
        # Placeholder for fetching the user's current API key if needed
        return render_template('apikey.html', login_username=login_username,api_key=current_api_key)
    else:
        user_id = request.json.get('user_id')
        if not user_id:
            return jsonify({'error': 'User ID is required'}), 400
        
        api_key = generate_api_key(user_id)
        key_id = upsert_api_key(user_id, api_key)
        
        if key_id is not None:
            return jsonify({'message': 'API key updated successfully', 'api_key': api_key, 'key_id': key_id})
        else:
            return jsonify({'error': 'Failed to update API key'}), 500

blueprints/core.py
from flask import Blueprint 
from flask import render_template, redirect, request, url_for
from database.user_db import add_user, find_user_by_username


core_bp = Blueprint('core_bp', __name__)

@core_bp.route('/')
def home():
    return render_template('index.html')

@core_bp.route('/download')
def download():
    return render_template('download.html')

@core_bp.route('/setup', methods=['GET', 'POST'])
def setup():
    if find_user_by_username() is not None:
        return redirect(url_for('auth.login'))

    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        mobile_number = request.form['mobile_number']
        # Add the new admin user
        if add_user(username, email, password, mobile_number, is_admin=True):
            return redirect(url_for('auth.login'))
        else:
            # If the user already exists or an error occurred, show an error message
            return 'User already exists or an error occurred'
    return render_template('setup.html')

blueprints/dashboard.py
from flask import Blueprint, render_template, session, redirect, url_for, g, jsonify, request
from database.auth_db import get_auth_token
from importlib import import_module
import multiprocessing
import sys



def dynamic_import(broker):
    try:
        module_path = f'broker.{broker}.api.funds'
        module = import_module(module_path)
        get_margin_data = getattr(module, 'get_margin_data')
        return get_margin_data
    except ImportError as e:
        print(f"Error importing module: {e}")
        return None

dashboard_bp = Blueprint('dashboard_bp', __name__, url_prefix='/')
scalper_process = None

@dashboard_bp.route('/dashboard')
def dashboard():
    if not session.get('logged_in'):
        return redirect(url_for('auth.login'))
    
    login_username = session['user']
    AUTH_TOKEN = get_auth_token(login_username)
    
    if AUTH_TOKEN is None:
        return redirect(url_for('auth.logout'))

    broker = session.get('broker')
    if not broker:
        return "Broker not set in session", 400
    
    get_margin_data_func = dynamic_import(broker)
    if get_margin_data_func is None:
        return "Failed to import broker module", 500

    margin_data = get_margin_data_func(AUTH_TOKEN)
    return render_template('dashboard.html', margin_data=margin_data)

blueprints/log.py
# blueprints/log.py

from flask import Blueprint, render_template, session, redirect, url_for
from database.apilog_db import OrderLog
from sqlalchemy import func
import pytz
from datetime import datetime

log_bp = Blueprint('log_bp', __name__, url_prefix='/logs')

@log_bp.route('/')
def view_logs():
    if not session.get('logged_in'):
        return redirect(url_for('auth.login'))

    # Set timezone to IST
    ist = pytz.timezone('Asia/Kolkata')
    
    # Get the current date in IST
    today_ist = datetime.now(ist).date()

    # Filter logs by today's date in IST
    logs = OrderLog.query.filter(func.date(OrderLog.created_at) == today_ist).order_by(OrderLog.created_at.desc()).all()

    return render_template('logs.html', logs=logs)

blueprints/search.py
from flask import Blueprint, render_template, session, redirect, url_for, request, flash
from database.symbol import search_symbols

search_bp = Blueprint('search_bp', __name__, url_prefix='/search')

@search_bp.route('/token')
def token():
    if not session.get('logged_in'):
        return redirect(url_for('auth_bp.login'))
    return render_template('token.html')

@search_bp.route('/')
def search():
    if not session.get('logged_in'):
        return redirect(url_for('auth_bp.login'))
    
    symbol = request.args.get('symbol')
    exchange = request.args.get('exchange')
    results = search_symbols(symbol,exchange)
    
    if not results:
        flash('No Matching Symbols Found.', 'error')
        return render_template('token.html')
    else:
        # Since results are now objects, we can't directly zip them with columns
        # Instead, we access attributes directly
        results_dicts = [{
            'symbol': result.symbol,
            'brsymbol': result.brsymbol,
            'name': result.name,
            'exchange': result.exchange,
            'brexchange': result.brexchange,
            'token': result.token,
            'expiry': result.expiry,
            'strike': result.strike,
            'lotsize': result.lotsize,
            'instrumenttype': result.instrumenttype,
            'tick_size': result.tick_size
        } for result in results]
        return render_template('search.html', results=results_dicts)

broker/__init__.py
"""
Empty file.
"""

templates/angel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AngelOne Authentication</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-900 flex flex-col items-center justify-center h-screen text-white">
    <div class="bg-gray-800 p-8 rounded-lg shadow-lg max-w-sm w-full">
        <div class="flex justify-center mb-6">
            <img class="h-20 w-auto" src="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}" alt="OpenAlgo">
        </div>
        <h2 class="text-3xl font-bold mb-6 text-center">Broker Authentication</h2>
        <form action="/angel/callback" method="POST" class="space-y-6">
            <div>
                <label for="clientid" class="block text-sm font-medium text-gray-300">Client ID</label>
                <input type="text" id="clientid" name="clientid" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
            </div>
            <div>
                <label for="pin" class="block text-sm font-medium text-gray-300">PIN</label>
                <input type="password" id="pin" name="pin" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
            </div>
            <div>
                <label for="totp" class="block text-sm font-medium text-gray-300">TOTP</label>
                <input type="password" id="totp" name="totp" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
            </div>
            <div class="flex items-center justify-center">
                <button type="submit" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Angel Login</button>
            </div>
            {% if error_message %}
            <div class="alert alert-danger" role="alert">
            {{ error_message }}
            </div>
            {% endif %}
        </form>
    </div>

    <!-- Include the footer content -->
    {% include 'footer.html' %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="OpenAlgo is your premier open source algorithmic trading platform, offering a robust and secure environment for developing and executing trading strategies.">
    <title>OpenAlgo</title>

    <!-- Favicon and touch icons for various devices -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='favicon/safari-pinned-tab.svg') }}" color="#5bbad5">
    
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.socket.io/4.0.0/socket.io.min.js"></script>
    <audio id="alert-sound" src="{{ url_for('static', filename='sounds/alert.mp3') }}" preload="auto"></audio>

    <script src="{{ url_for('static', filename='js/socket-events.js') }}"></script>
    <script src="{{ url_for('static', filename='js/mobile-menu.js') }}"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    

    <!-- Meta tags for color settings on mobile browsers -->
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <style>
        /* Style in base.html to control the flash message container's spacing */
        .flash-message-container {
            margin-bottom: 0; /* Remove bottom margin */
            padding-bottom: 0; /* Remove bottom padding */
        }
    </style>

    {% block head %}{% endblock %}
</head>
<body class="bg-white-100">
    {% include 'navbar.html' %}

    <!-- Flash Messages Display Area -->
    <div class="container mx-auto mt-4 flash-message-container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="w-full px-4 py-3 mx-auto">
                    {% for category, message in messages %}
                        <div class="
                            {{ 'bg-green-100 text-green-800' if category == 'success' else 'bg-red-100 text-red-800' }}
                            px-4 py-3 rounded relative text-center" role="alert">
                            <strong class="font-bold">{{ message }}</strong>
                            <!-- Optional close button for the alert, if you want it -->
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>

    <!-- Adjusted Main Content Area to avoid overlap with the new navbar -->
    <div class="container mx-auto mt-24">
        {% block content %}{% endblock %}
    </div>

    <!-- Include the footer content -->
    {% include 'footer.html' %}

    <script>
    document.getElementById('profileBtn').addEventListener('click', function() {
        var dropdown = document.getElementById('profileMenu');
        dropdown.classList.toggle('hidden');
    });
    </script>        
</body>
</html>

templates/broker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trading Account Authentication - OpenAlgo</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <!-- Favicon and touch icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='favicon/safari-pinned-tab.svg') }}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
</head>
<body class="bg-gray-900 flex flex-col items-center justify-center min-h-screen text-white">
    <div class="p-8 rounded-lg shadow-lg max-w-md w-full bg-gray-800">
        <div class="flex justify-center mb-6">
            <img class="h-20 w-auto" src="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}" alt="OpenAlgo">
        </div>
        <h2 class="text-3xl font-bold mb-6 text-center">Connect Your Trading Account</h2>
        
        <form id="trading-platform-form" class="space-y-6">
            <div>
                <label for="platform-select" class="block text-sm font-medium text-gray-300 mb-2">Login with your Broker</label>
                <select id="platform-select" name="platform" class="block w-full px-3 py-2 text-base border border-gray-600 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-gray-700 text-white">
                    <option value="" selected disabled>Select a Broker</option>
                    <option value="fivepaisa">5 Paisa</option>
                    <option value="aliceblue">Alice Blue</option>
                    <option value="angel">Angel One</option>
                    <option value="dhan">Dhan</option>
                    <option value="fyers">Fyers</option>
                    <option value="icici">ICICI Direct</option>
                    <option value="kotak">Kotak Securities</option>
                    <option value="upstox">Upstox</option>
                    <option value="zebu">Zebu</option>
                    <option value="zerodha">Zerodha</option>
                </select>
            </div>
            <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                Connect Account
            </button>
        </form>
    </div>
    
    <!-- Include the footer content -->
    {% include 'footer.html' %}

    <script>
        document.getElementById('trading-platform-form').addEventListener('submit', function(e) {
            e.preventDefault();
            const platform = document.getElementById('platform-select').value;
            let loginUrl;

            switch(platform) {
                case 'fivepaisa':
                    loginUrl = '/fivepaisa/callback';
                    break;
                case 'aliceblue':
                    loginUrl = '/aliceblue/callback';
                    break;
                case 'angel':
                    loginUrl = '/angel/callback';
                    break;
                case 'dhan':
                    loginUrl = '/dhan/callback';
                    break;
                case 'fyers':
                    loginUrl = 'https://api-t1.fyers.in/api/v3/generate-authcode?client_id={{broker_api_key}}&redirect_uri={{redirect_url}}&response_type=code&state=2e9b44629ebb28226224d09db3ffb47c';
                    break;
                case 'icici':
                    loginUrl = 'https://api.icicidirect.com/apiuser/login?api_key={{broker_api_key}}';
                    break;
                case 'kotak':
                    loginUrl = '/kotak/callback';
                    break;
                case 'upstox':
                    loginUrl = 'https://api.upstox.com/v2/login/authorization/dialog?response_type=code&client_id={{broker_api_key}}&redirect_uri={{ redirect_url }}';
                    break;
                case 'zebu':
                    loginUrl = '/zebu/callback';
                    break;
                case 'zerodha':
                    loginUrl = 'https://kite.trade/connect/login?api_key={{broker_api_key}}';
                    break;
                default:
                    alert('Please select a broker');
                    return;
            }

            window.location.href = loginUrl;
        });
    </script>
</body>
</html>

templates/kotak.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kotak Authentication</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-900 flex flex-col items-center justify-center h-screen text-white">
    <div class="bg-gray-800 p-8 rounded-lg shadow-lg max-w-sm w-full">
        <div class="flex justify-center mb-6">
            <img class="h-20 w-auto" src="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}" alt="OpenAlgo">
        </div>
        <h2 class="text-3xl font-bold mb-6 text-center">Broker Authentication</h2>
        <form action="/kotak/loginflow" method="POST" class="space-y-6">
            <div>
                <label for="clientid" class="block text-sm font-medium text-gray-300">Mobile Number (e.g +919999955555 )</label>
                <input type="text" id="clientid" name="mobilenumber" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
            </div>
            <div>
                <label for="pin" class="block text-sm font-medium text-gray-300">Password</label>
                <input type="password" id="pin" name="password" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
            </div>
            <div class="flex items-center justify-center">
                <button type="submit" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Kotak Login</button>
            </div>
            {% if error_message %}
            <div class="alert alert-danger" role="alert">
            {{ error_message }}
            </div>
            {% endif %}
        </form>
    </div>

    <!-- Include the footer content -->
    {% include 'footer.html' %}
</body>
</html>

templates/search.html
{% extends "base.html" %}

{% block head %}
    <title>Search Results</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- Add any additional head content for search.html here -->
{% endblock %}

{% block content %}
<div class="container mx-auto px-4 bg-gray-100 min-h-screen">
    <h1 class="text-xl font-semibold text-center mb-4">Search Results</h1>
    <p class="text-center mb-4">Found {{ results|length }} matching symbols.</p>
    <div class="overflow-x-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
            <thead>
                <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b bg-gray-50">
                    
                    <th class="px-4 py-3">OpenAlgo Symbol</th>
                    <th class="px-4 py-3">Broker Symbol</th>
                    <th class="px-4 py-3">Name</th>
                    <th class="px-4 py-3">OpenAlgo Exchange</th>
                    <th class="px-4 py-3">Broker Exchange</th>
                    <th class="px-4 py-3">Token</th>
                    <th class="px-4 py-3">Expiry</th>
                    <th class="px-4 py-3">Strike</th>
                    <th class="px-4 py-3">Lot Size</th>
                    <!-- <th class="px-4 py-3">Instrument Type</th> -->
                    <!-- <th class="px-4 py-3">Tick Size</th> -->
                </tr>
            </thead>
            <tbody class="bg-white divide-y">
                {% for row in results %}
                <tr class="text-gray-700">
                    <td class="px-4 py-3">{{ row.symbol }}</td>
                    <td class="px-4 py-3">{{ row.brsymbol }}</td>
                    <td class="px-4 py-3">{{ row.name }}</td>
                    <td class="px-4 py-3">{{ row.exchange }}</td>
                    <td class="px-4 py-3">{{ row.brexchange }}</td>
                    <td class="px-4 py-3">{{ row.token }}</td>
                    <td class="px-4 py-3">{{ row.expiry }}</td>
                    <td class="px-4 py-3">{{ row.strike }}</td>
                    <td class="px-4 py-3">{{ row.lotsize }}</td>
                    <!-- <td class="px-4 py-3">{{ row.instrumenttype }}</td> -->
                    <!-- <td class="px-4 py-3">{{ row.tick_size }}</td> -->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="text-center mt-4">
        <a href="{{ url_for('search_bp.token') }}" class="text-blue-500 hover:underline">New search</a>
    </div>
</div>
{% endblock %}

templates/setup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup OpenAlgo Account</title>
    <!-- Favicon and touch icons for various devices -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='favicon/safari-pinned-tab.svg') }}" color="#5bbad5">
    
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const password = document.getElementById('password');
            const confirmPassword = document.getElementById('confirm_password');
            const validationMessage = document.getElementById('validation-message');
            const submitButton = document.querySelector('button[type="submit"]');
            
            function validatePasswordPolicy(password) {
                return /^(?=.*\d)(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z]).{8,}$/.test(password);
            }

            function handleValidation() {
                const passwordsMatch = password.value === confirmPassword.value;
                const passwordIsValid = validatePasswordPolicy(password.value);

                if (passwordsMatch && passwordIsValid) {
                    validationMessage.textContent = "Password matched";
                    validationMessage.style.color = "green";
                    submitButton.disabled = false;
                } else {
                    validationMessage.textContent = passwordsMatch ? "Password does not meet policy" : "Password not matched";
                    validationMessage.style.color = "red";
                    submitButton.disabled = true;
                }

                document.getElementById('password-policy').style.display = passwordIsValid ? 'none' : 'block';
            }

            password.onchange = handleValidation;
            confirmPassword.onkeyup = handleValidation;
        });
    </script>
</head>
<body class="bg-gray-900 flex flex-col items-center justify-center h-screen text-white">
    <div class="bg-gray-800 p-8 rounded-lg shadow-lg max-w-sm w-full">
        <h2 class="text-3xl font-bold mb-6 text-center">Setup OpenAlgo Account</h2>
        <form action="{{ url_for('core_bp.setup') }}" method="post" class="space-y-6" id="setupForm">
            <div>
                <label for="username" class="block text-sm font-medium text-gray-300">Username</label>
                <input type="text" id="username" name="username" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
            </div>
            <div>
                <label for="password" class="block text-sm font-medium text-gray-300">Password</label>
                <input type="password" id="password" name="password" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500" pattern="^(?=.*\d)(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z]).{8,}$" title="Password must contain at least 8 characters, including 1 uppercase, 1 lowercase, 1 number and 1 special character.">
            </div>
            <div>
                <label for="confirm_password" class="block text-sm font-medium text-gray-300">Confirm Password</label>
                <input type="password" id="confirm_password" name="confirm_password" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
                <span id="validation-message"></span>
            </div>
            <div>
                <label for="email" class="block text-sm font-medium text-gray-300">Email</label>
                <input type="email" id="email" name="email" required class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
            </div>
            <div>
                <label for="mobile_number" class="block text-sm font-medium text-gray-300">Mobile Number</label>
                <input type="tel" id="mobile_number" name="mobile_number" required pattern="[0-9]{10,15}" class="mt-1 block w-full px-3 py-2 bg-gray-700 text-gray-300 border-gray-600 rounded-md shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500">
            </div>
            <div class="flex items-center justify-center">
                <button type="submit" disabled class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Setup</button>
            </div>
            <div id="password-policy" class="text-sm mt-4" style="color: yellow;">
                <p>Password Policy Guidelines:</p>
                <ul class="list-disc pl-5">
                    <li>Minimum 8 characters</li>
                    <li>At least 1 uppercase letter (A-Z)</li>
                    <li>At least 1 lowercase letter (a-z)</li>
                    <li>At least 1 number (0-9)</li>
                    <li>At least 1 special symbol (@, #, $, etc.)</li>
                </ul>
            </div>
        </form>
    </div>
</body>
</html>